export type RuleId =
  | "CANONICAL_TERM"
  | "REQUIRED_DOCUMENT"
  | "REQUIRED_SECTION"
  | "REQUIRED_FIELD"
  | "STATUS_VOCABULARY"
  | "IMPLEMENTATION_BOUNDARY"
  | "SENSITIVE_PATTERN"
  | "API_SPEC_TABLE"
  | "API_TASK_LINK"
  | "TASK_ID_TRIAD"
  | "PERMISSION_COMPLETION"
  | "PERMISSION_OPEN_QUESTION";
