import type { ValidationIssue } from "../model/ValidationIssue.js";
import type { ValidationResult } from "../model/ValidationResult.js";

export interface MarkdownReportInput {
  root: string;
  markdownFileCount: number;
  validationResult: ValidationResult;
}

export function buildMarkdownReport(input: MarkdownReportInput): string {
  const { root, markdownFileCount, validationResult } = input;
  const result = validationResult.hasErrors ? "Failed" : "Passed";

  return [
    "# Validation Report",
    "",
    "## Summary",
    "",
    `- Root: \`${escapeInlineCode(root)}\``,
    `- Markdown files scanned: ${markdownFileCount}`,
    `- Errors: ${validationResult.errorCount}`,
    `- Warnings: ${validationResult.warningCount}`,
    `- Result: ${result}`,
    "",
    "## Issues",
    "",
    buildIssuesSection(validationResult.issues),
    "",
    "## Read-only Guarantee",
    "",
    "No source files under the input root were modified.",
    "",
    "## Notes",
    "",
    "- This report is generated by the Local CLI Validator PoC.",
    "- Domain meaning judgement is out of scope.",
    "- Auto-fix is not performed.",
    "",
  ].join("\n");
}

function buildIssuesSection(issues: readonly ValidationIssue[]): string {
  if (issues.length === 0) {
    return "No issues found.";
  }

  const rows = [...issues].sort(compareIssues).map((issue) =>
    [
      issue.severity,
      issue.ruleId,
      issue.file ?? "",
      issue.line?.toString() ?? "",
      issue.message,
    ]
      .map(escapeTableCell)
      .join(" | "),
  );

  return [
    "| Severity | Rule | File | Line | Message |",
    "|---|---|---|---:|---|",
    ...rows.map((row) => `| ${row} |`),
  ].join("\n");
}

function compareIssues(
  left: ValidationIssue,
  right: ValidationIssue,
): number {
  return (
    severityRank(left) - severityRank(right) ||
    left.ruleId.localeCompare(right.ruleId) ||
    compareOptionalString(left.file, right.file) ||
    compareOptionalNumber(left.line, right.line) ||
    left.message.localeCompare(right.message)
  );
}

function severityRank(issue: ValidationIssue): number {
  return issue.severity === "error" ? 0 : 1;
}

function compareOptionalString(
  left: string | undefined,
  right: string | undefined,
): number {
  if (left === undefined) return right === undefined ? 0 : 1;
  if (right === undefined) return -1;
  return left.localeCompare(right);
}

function compareOptionalNumber(
  left: number | undefined,
  right: number | undefined,
): number {
  if (left === undefined) return right === undefined ? 0 : 1;
  if (right === undefined) return -1;
  return left - right;
}

function escapeTableCell(value: string): string {
  return value.replace(/\r?\n/gu, " ").replace(/\|/gu, "\\|");
}

function escapeInlineCode(value: string): string {
  return value.replace(/`/gu, "\\`");
}
